source :rubygems
source "http://gems.github.com"
gem "roauth", ">= 0.0.2"
gem "eventmachine", ">= 0.12.8"
gem "twitter-stream", "=0.1.10"
gem "json", ">= 1.4.3"
gem "em-http-request", ">= 0.2.10"
gem "rake"
gem "twitter-text", "=1.3.0"
gem "twitter", "=1.0.0"
gem "couchrest"
gem "couchrest_model"
gem "hoptoad_notifier"
gem "right_aws"
