twitter:
  username: #twitter username
  password: #twitter password
  track_word: @ # We track '@' so we can receive all the mentions to usernames among many other things
hoptoad:
  api_key: # This project has lot of background processes so some notification service such as Hoptoad is extremely useful
